openapi: 3.1.0
info:
  version: 1.0.0
  title: API First with Spring Boot
  termsOfService: https://example.com/terms/
  contact:
    name: Contact our support
    email: danilo.ro@proton.me
    url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification.
    
tags:
  - name: Customer
    description: "Customer operations."
  - name: Product
    description: "Product operations."
  - name: Order
    description: "Order operations."

servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1

paths:
  '/v1/customers':
    $ref: 'paths/v1/customers.yaml'
  '/v1/customers/{id}':
    $ref: 'paths/v1/customers_{id}.yaml'
  '/v1/products':
    $ref: 'paths/v1/products.yaml'
  '/v1/products/{id}':
    $ref: 'paths/v1/products_{id}.yaml'
  '/v1/orders':
    $ref: 'paths/v1/orders.yaml'
  '/v1/orders/{id}':
    $ref: 'paths/v1/orders_{id}.yaml'

security:
  - basic_auth: []

components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic

